language: node_js
node_js: stable
before_script:
- bower install --silent
addons:
  sauce_connect: true
script:
- npm run lint
- polymer test --plugin sauce --job-name "chrome-file-export:${TRAVIS_BRANCH}" --build-number=${TRAVIS_BUILD_NUMBER}
cache:
  directories:
  - node_modules
branches:
  only:
  - stage
  - develop
after_success:
- node tasks/ci.js
env:
  global:
  - secure: geNEssE11p96mN/7rXt/A6XEkd6r70BlUeXwKPkzeslEj5DeV6yuUj/MMUO5QUEBClS0wV6v+Wr0pouW+rt/5MvgUNo/l8cNMfrC2XlFurl03+4mJLwOm0LQ8z22zN5K0v7StdX4z/iP2PNW9qvGLdEJsXHc5OvCR/HIo+InLOWKIgdctKL6jcaRIM1RbUvnsX0b33r3hNzRuX8o9f5FLWoMMVf8WzgL1P28naZH1tuZjSJDMlQXtuYU9z7gKXpvjJWGz0efOo/bDaYBy3DOuiBDQJC0SfwKwimja7n7c5gD4+s0lTXUASU7wk4CqOZ+pzL2jl7DDLxlZQzTMUeP1i6dZCEpQOWk1m4XDKLtkymg7lZQN/k/NiceOL6Tp4hYg/E5SxK3xszoBK2W8vO/88VspdWM/8fHI4//QkPkqVaIKyu8zwTmnHRU4byjne+TxsO2nY76gsTOmVfXfklDMoJ0x5kIvdxOkhew93WuWUdXch44kN8VkQ57ol0MVJvzhWsYuhXNrJ6qMtzFhETwO7kDr3BxqPcULZHaWsPtAzwsIkhPFxNP8n050Kr4IucT5j16PT58bs62EObdKbtH5xSfkhPcDTvzGpIYsR3KhSHFlBpbfNV91/nVpcxiAIHNEVE5TCtrrnQueTKI6+MnXeNbrYHoLDQ1Yxt3mAAFmAQ=
  - secure: ZnYmsRi/ifyKKjn45AZYh1V5aLcnnYjvcPCW0AiMyMoKDdUXN5ZsNbHlHlI2YGZcm8Yv8Np9cG9ulmIJHrqTnrykh9Df09AsITbM82nnMpFLq9pH23jY4rFyo6dlVtvho6vv365zqwh+/Y9owwTSQwTHDpFWCCx5mpKUM2SNCBu3m2nQo0JWVdSlJgq6Qv7/lTEw9hznP+5jykxJoawV9QDw4Ife4fkqn0+uHIdv9zfXy947ne1wUnrGS0/cicOGMiHuimgwjA0haI8sCb691baRLVz0MZhf9jQWMVqA5GHEDfHCL3APimc/PdTXx5iQF4XQNxZG7cb7a15WOw3nwyNfOIZT5g80NlmDQ9Z9YQVeFtnzgS5MrwVplOywlSGAYUfnp1gtYgl0cG3O4fXOGCjCFtHHwMHUivHsf5Xgx7obpA2O6mbNpvGcJiYu/5m0gy8+g57wJqnP7pvWuB7qVZmXHbofCVq/fijWOuxdsD3a8HMxz769oqYYE9UaW969KqhVQsVujE1yZH4gVj4FU3EFjfbgUNdc56rwc7+RIteqA5sOd0A6kEQxdeVi+LrKZYzQvRMVdUV23Jo4aOjQDta1B7XNHP9zqL1n/4wYP2/nSWx2YUB2Tl4UcjJBqv71+nOpapdSHGaIQoTJ4vx94P/MwlXwHoEFbwv2+E9aC/I=
